# ローカル用

services:
  db:
    image: mysql:8.4
    platform: linux/amd64
    container_name: nekodion-db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: nekodion
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: Asia/Tokyo
    ports:
      - "127.0.0.1:3368:3306"
    volumes:
      - nekodion_db_data:/var/lib/mysql
    networks:
      - nekodion-net
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 10

  flyway:
    image: flyway/flyway:11
    platform: linux/amd64
    container_name: nekodion-flyway
    environment:
      FLYWAY_URL: jdbc:mysql://db:3306/nekodion?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Tokyo
      FLYWAY_USER: user
      FLYWAY_PASSWORD: pass
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nekodion-net

volumes:
  nekodion_db_data:
networks:
  nekodion-net:
